// This file is auto-generated by @hey-api/openapi-ts

import type {
  RegisterAuthRegisterPostResponse,
  GetCurrentUserInfoAuthMeGetResponse,
} from './types.gen';

const userResponseSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  return data;
};

export const registerAuthRegisterPostResponseTransformer = async (
  data: any,
): Promise<RegisterAuthRegisterPostResponse> => {
  data = userResponseSchemaResponseTransformer(data);
  return data;
};

export const getCurrentUserInfoAuthMeGetResponseTransformer = async (
  data: any,
): Promise<GetCurrentUserInfoAuthMeGetResponse> => {
  data = userResponseSchemaResponseTransformer(data);
  return data;
};
