// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

/**
 * Body_upload_kb_kb_upload_post
 */
export const zBodyUploadKbKbUploadPost = z.object({
  file: z.string(),
});

/**
 * ChatRequest
 */
export const zChatRequest = z.object({
  message: z.string(),
});

/**
 * DataSourceInfo
 */
export const zDataSourceInfo = z.object({
  id: z.string(),
  name: z.string(),
  description: z.string(),
  tables: z.array(z.string()),
  access_level: z.string(),
  has_access: z.boolean(),
});

/**
 * FileInfo
 */
export const zFileInfo = z.object({
  filename: z.string(),
  size: z.number().int(),
  upload_date: z.string(),
  file_type: z.string(),
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
  loc: z.array(z.union([z.string(), z.number().int()])),
  msg: z.string(),
  type: z.string(),
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
  detail: z.array(zValidationError).optional(),
});

/**
 * UserCreate
 */
export const zUserCreate = z.object({
  username: z.string(),
  password: z.string(),
  email: z.string().optional().default(''),
  full_name: z.string().optional().default(''),
});

/**
 * UserLogin
 */
export const zUserLogin = z.object({
  username: z.string(),
  password: z.string(),
});

/**
 * UserResponse
 */
export const zUserResponse = z.object({
  id: z.string(),
  username: z.string(),
  email: z.string(),
  full_name: z.string(),
  created_at: z.string().datetime(),
  role: z.string().optional().default('user'),
});

/**
 * UserSettingsResponse
 */
export const zUserSettingsResponse = z.object({
  vai_tro: z.string(),
  chi_nhanh: z.string(),
  pham_vi: z.string(),
  du_lieu: z.string(),
  datasource_permissions: z.array(z.string()),
});

/**
 * UserSettingsUpdate
 */
export const zUserSettingsUpdate = z.object({
  vai_tro: z.string(),
  chi_nhanh: z.string(),
  pham_vi: z.string(),
  du_lieu: z.string(),
  datasource_permissions: z.array(z.string()),
});

export const zRegisterAuthRegisterPostData = z.object({
  body: zUserCreate,
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * Successful Response
 */
export const zRegisterAuthRegisterPostResponse = zUserResponse;

export const zLoginAuthLoginPostData = z.object({
  body: zUserLogin,
  path: z.never().optional(),
  query: z.never().optional(),
});

export const zLogoutAuthLogoutPostData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

export const zGetCurrentUserInfoAuthMeGetData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * Successful Response
 */
export const zGetCurrentUserInfoAuthMeGetResponse = zUserResponse;

export const zSendMessageChatMessagePostData = z.object({
  body: zChatRequest,
  path: z.never().optional(),
  query: z.never().optional(),
});

export const zGetChatHistoryChatHistoryGetData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

export const zDeleteChatByIdChatHistoryIdDeleteData = z.object({
  body: z.never().optional(),
  path: z.object({
    id: z.string(),
  }),
  query: z.never().optional(),
});

export const zGetChatByIdChatHistoryIdGetData = z.object({
  body: z.never().optional(),
  path: z.object({
    id: z.string(),
  }),
  query: z.never().optional(),
});

export const zContinueChatChatContinueChatIdPostData = z.object({
  body: zChatRequest,
  path: z.object({
    chat_id: z.string(),
  }),
  query: z.never().optional(),
});

export const zGetChatDataChatDataChatIdGetData = z.object({
  body: z.never().optional(),
  path: z.object({
    chat_id: z.string(),
  }),
  query: z.never().optional(),
});

export const zUploadKbKbUploadPostData = z.object({
  body: zBodyUploadKbKbUploadPost,
  path: z.never().optional(),
  query: z.never().optional(),
});

export const zListKbKbListGetData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * Response List Kb Kb List Get
 * Successful Response
 */
export const zListKbKbListGetResponse = z.array(zFileInfo);

export const zDeleteKbKbFilenameDeleteData = z.object({
  body: z.never().optional(),
  path: z.object({
    filename: z.string(),
  }),
  query: z.never().optional(),
});

export const zDownloadKbKbDownloadFilenameGetData = z.object({
  body: z.never().optional(),
  path: z.object({
    filename: z.string(),
  }),
  query: z.never().optional(),
});

export const zDownloadChatDataQueryDownloadChatIdGetData = z.object({
  body: z.never().optional(),
  path: z.object({
    chat_id: z.string(),
  }),
  query: z.object({
    format: z.enum(['csv', 'excel', 'pdf']),
  }),
});

export const zDownloadSampleQueryDownloadGetData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

export const zValidateQueryQueryValidateGetData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.object({
    sql_query: z.string(),
  }),
});

export const zGetSettingsUserSettingsGetData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * Successful Response
 */
export const zGetSettingsUserSettingsGetResponse = zUserSettingsResponse;

export const zUpdateSettingsUserSettingsPostData = z.object({
  body: zUserSettingsUpdate,
  path: z.never().optional(),
  query: z.never().optional(),
});

export const zGetDatasourcesUserDatasourcesGetData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * Response Get Datasources User Datasources Get
 * Successful Response
 */
export const zGetDatasourcesUserDatasourcesGetResponse = z.array(zDataSourceInfo);

export const zGetAccessibleDatasourcesUserDatasourcesAccessibleGetData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * Response Get Accessible Datasources User Datasources Accessible Get
 * Successful Response
 */
export const zGetAccessibleDatasourcesUserDatasourcesAccessibleGetResponse =
  z.array(zDataSourceInfo);

export const zRequestDatasourceAccessUserDatasourcesDatasourceIdRequestAccessPostData = z.object({
  body: z.never().optional(),
  path: z.object({
    datasource_id: z.string(),
  }),
  query: z.never().optional(),
});

export const zGetUserProfileUserProfileGetData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

export const zHealthCheckMetricsHealthGetData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

export const zRootGetData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});
