version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: querypilot
      POSTGRES_PASSWORD: querypilot
      POSTGRES_DB: querypilot
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: querypilot@gmail.com
      PGADMIN_DEFAULT_PASSWORD: querypilot
    ports:
      - '5050:80'
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin-data:
