// This file is auto-generated by @hey-api/openapi-ts

import type { GetCurrentUserInfoAuthMeGetResponse } from './types.gen';

const userResponseSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  return data;
};

export const getCurrentUserInfoAuthMeGetResponseTransformer = async (
  data: any,
): Promise<GetCurrentUserInfoAuthMeGetResponse> => {
  data = userResponseSchemaResponseTransformer(data);
  return data;
};
