// This file is auto-generated by @hey-api/openapi-ts

/**
 * Body_upload_kb_kb_upload_post
 */
export type BodyUploadKbKbUploadPost = {
  /**
   * File
   */
  file: Blob | File;
};

/**
 * ChatRequest
 */
export type ChatRequest = {
  /**
   * Message
   */
  message: string;
};

/**
 * DataSourceInfo
 */
export type DataSourceInfo = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description: string;
  /**
   * Tables
   */
  tables: Array<string>;
  /**
   * Access Level
   */
  access_level: string;
  /**
   * Has Access
   */
  has_access: boolean;
};

/**
 * FileInfo
 */
export type FileInfo = {
  /**
   * Filename
   */
  filename: string;
  /**
   * Size
   */
  size: number;
  /**
   * Upload Date
   */
  upload_date: string;
  /**
   * File Type
   */
  file_type: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * UserCreate
 */
export type UserCreate = {
  /**
   * Username
   */
  username: string;
  /**
   * Password
   */
  password: string;
  /**
   * Email
   */
  email?: string;
  /**
   * Full Name
   */
  full_name?: string;
};

/**
 * UserLogin
 */
export type UserLogin = {
  /**
   * Username
   */
  username: string;
  /**
   * Password
   */
  password: string;
};

/**
 * UserResponse
 */
export type UserResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Username
   */
  username: string;
  /**
   * Email
   */
  email: string;
  /**
   * Full Name
   */
  full_name: string;
  /**
   * Created At
   */
  created_at: Date;
  /**
   * Role
   */
  role?: string;
};

/**
 * UserSettingsResponse
 */
export type UserSettingsResponse = {
  /**
   * Vai Tro
   */
  vai_tro: string;
  /**
   * Chi Nhanh
   */
  chi_nhanh: string;
  /**
   * Pham Vi
   */
  pham_vi: string;
  /**
   * Du Lieu
   */
  du_lieu: string;
  /**
   * Datasource Permissions
   */
  datasource_permissions: Array<string>;
};

/**
 * UserSettingsUpdate
 */
export type UserSettingsUpdate = {
  /**
   * Vai Tro
   */
  vai_tro: string;
  /**
   * Chi Nhanh
   */
  chi_nhanh: string;
  /**
   * Pham Vi
   */
  pham_vi: string;
  /**
   * Du Lieu
   */
  du_lieu: string;
  /**
   * Datasource Permissions
   */
  datasource_permissions: Array<string>;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
};

export type RegisterAuthRegisterPostData = {
  body: UserCreate;
  path?: never;
  query?: never;
  url: '/auth/register';
};

export type RegisterAuthRegisterPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RegisterAuthRegisterPostError =
  RegisterAuthRegisterPostErrors[keyof RegisterAuthRegisterPostErrors];

export type RegisterAuthRegisterPostResponses = {
  /**
   * Successful Response
   */
  200: UserResponse;
};

export type RegisterAuthRegisterPostResponse =
  RegisterAuthRegisterPostResponses[keyof RegisterAuthRegisterPostResponses];

export type LoginAuthLoginPostData = {
  body: UserLogin;
  path?: never;
  query?: never;
  url: '/auth/login';
};

export type LoginAuthLoginPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type LoginAuthLoginPostError = LoginAuthLoginPostErrors[keyof LoginAuthLoginPostErrors];

export type LoginAuthLoginPostResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type LogoutAuthLogoutPostData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/auth/logout';
};

export type LogoutAuthLogoutPostResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetCurrentUserInfoAuthMeGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/auth/me';
};

export type GetCurrentUserInfoAuthMeGetResponses = {
  /**
   * Successful Response
   */
  200: UserResponse;
};

export type GetCurrentUserInfoAuthMeGetResponse =
  GetCurrentUserInfoAuthMeGetResponses[keyof GetCurrentUserInfoAuthMeGetResponses];

export type SendMessageChatMessagePostData = {
  body: ChatRequest;
  path?: never;
  query?: never;
  url: '/chat/message';
};

export type SendMessageChatMessagePostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SendMessageChatMessagePostError =
  SendMessageChatMessagePostErrors[keyof SendMessageChatMessagePostErrors];

export type SendMessageChatMessagePostResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetChatHistoryChatHistoryGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/chat/history';
};

export type GetChatHistoryChatHistoryGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type DeleteChatByIdChatHistoryIdDeleteData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: '/chat/history/{id}';
};

export type DeleteChatByIdChatHistoryIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteChatByIdChatHistoryIdDeleteError =
  DeleteChatByIdChatHistoryIdDeleteErrors[keyof DeleteChatByIdChatHistoryIdDeleteErrors];

export type DeleteChatByIdChatHistoryIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetChatByIdChatHistoryIdGetData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: '/chat/history/{id}';
};

export type GetChatByIdChatHistoryIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetChatByIdChatHistoryIdGetError =
  GetChatByIdChatHistoryIdGetErrors[keyof GetChatByIdChatHistoryIdGetErrors];

export type GetChatByIdChatHistoryIdGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ContinueChatChatContinueChatIdPostData = {
  body: ChatRequest;
  path: {
    /**
     * Chat Id
     */
    chat_id: string;
  };
  query?: never;
  url: '/chat/continue/{chat_id}';
};

export type ContinueChatChatContinueChatIdPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ContinueChatChatContinueChatIdPostError =
  ContinueChatChatContinueChatIdPostErrors[keyof ContinueChatChatContinueChatIdPostErrors];

export type ContinueChatChatContinueChatIdPostResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetChatDataChatDataChatIdGetData = {
  body?: never;
  path: {
    /**
     * Chat Id
     */
    chat_id: string;
  };
  query?: never;
  url: '/chat/data/{chat_id}';
};

export type GetChatDataChatDataChatIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetChatDataChatDataChatIdGetError =
  GetChatDataChatDataChatIdGetErrors[keyof GetChatDataChatDataChatIdGetErrors];

export type GetChatDataChatDataChatIdGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type UploadKbKbUploadPostData = {
  body: BodyUploadKbKbUploadPost;
  path?: never;
  query?: never;
  url: '/kb/upload';
};

export type UploadKbKbUploadPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UploadKbKbUploadPostError =
  UploadKbKbUploadPostErrors[keyof UploadKbKbUploadPostErrors];

export type UploadKbKbUploadPostResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ListKbKbListGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/kb/list';
};

export type ListKbKbListGetResponses = {
  /**
   * Response List Kb Kb List Get
   * Successful Response
   */
  200: Array<FileInfo>;
};

export type ListKbKbListGetResponse = ListKbKbListGetResponses[keyof ListKbKbListGetResponses];

export type DeleteKbKbFilenameDeleteData = {
  body?: never;
  path: {
    /**
     * Filename
     */
    filename: string;
  };
  query?: never;
  url: '/kb/{filename}';
};

export type DeleteKbKbFilenameDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteKbKbFilenameDeleteError =
  DeleteKbKbFilenameDeleteErrors[keyof DeleteKbKbFilenameDeleteErrors];

export type DeleteKbKbFilenameDeleteResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type DownloadKbKbDownloadFilenameGetData = {
  body?: never;
  path: {
    /**
     * Filename
     */
    filename: string;
  };
  query?: never;
  url: '/kb/download/{filename}';
};

export type DownloadKbKbDownloadFilenameGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DownloadKbKbDownloadFilenameGetError =
  DownloadKbKbDownloadFilenameGetErrors[keyof DownloadKbKbDownloadFilenameGetErrors];

export type DownloadKbKbDownloadFilenameGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type DownloadChatDataQueryDownloadChatIdGetData = {
  body?: never;
  path: {
    /**
     * Chat Id
     */
    chat_id: string;
  };
  query: {
    /**
     * Format
     */
    format: 'csv' | 'excel' | 'pdf';
  };
  url: '/query/download/{chat_id}';
};

export type DownloadChatDataQueryDownloadChatIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DownloadChatDataQueryDownloadChatIdGetError =
  DownloadChatDataQueryDownloadChatIdGetErrors[keyof DownloadChatDataQueryDownloadChatIdGetErrors];

export type DownloadChatDataQueryDownloadChatIdGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type DownloadSampleQueryDownloadGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/query/download';
};

export type DownloadSampleQueryDownloadGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ValidateQueryQueryValidateGetData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Sql Query
     */
    sql_query: string;
  };
  url: '/query/validate';
};

export type ValidateQueryQueryValidateGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ValidateQueryQueryValidateGetError =
  ValidateQueryQueryValidateGetErrors[keyof ValidateQueryQueryValidateGetErrors];

export type ValidateQueryQueryValidateGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetSettingsUserSettingsGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/user/settings';
};

export type GetSettingsUserSettingsGetResponses = {
  /**
   * Successful Response
   */
  200: UserSettingsResponse;
};

export type GetSettingsUserSettingsGetResponse =
  GetSettingsUserSettingsGetResponses[keyof GetSettingsUserSettingsGetResponses];

export type UpdateSettingsUserSettingsPostData = {
  body: UserSettingsUpdate;
  path?: never;
  query?: never;
  url: '/user/settings';
};

export type UpdateSettingsUserSettingsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateSettingsUserSettingsPostError =
  UpdateSettingsUserSettingsPostErrors[keyof UpdateSettingsUserSettingsPostErrors];

export type UpdateSettingsUserSettingsPostResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetDatasourcesUserDatasourcesGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/user/datasources';
};

export type GetDatasourcesUserDatasourcesGetResponses = {
  /**
   * Response Get Datasources User Datasources Get
   * Successful Response
   */
  200: Array<DataSourceInfo>;
};

export type GetDatasourcesUserDatasourcesGetResponse =
  GetDatasourcesUserDatasourcesGetResponses[keyof GetDatasourcesUserDatasourcesGetResponses];

export type GetAccessibleDatasourcesUserDatasourcesAccessibleGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/user/datasources/accessible';
};

export type GetAccessibleDatasourcesUserDatasourcesAccessibleGetResponses = {
  /**
   * Response Get Accessible Datasources User Datasources Accessible Get
   * Successful Response
   */
  200: Array<DataSourceInfo>;
};

export type GetAccessibleDatasourcesUserDatasourcesAccessibleGetResponse =
  GetAccessibleDatasourcesUserDatasourcesAccessibleGetResponses[keyof GetAccessibleDatasourcesUserDatasourcesAccessibleGetResponses];

export type RequestDatasourceAccessUserDatasourcesDatasourceIdRequestAccessPostData = {
  body?: never;
  path: {
    /**
     * Datasource Id
     */
    datasource_id: string;
  };
  query?: never;
  url: '/user/datasources/{datasource_id}/request-access';
};

export type RequestDatasourceAccessUserDatasourcesDatasourceIdRequestAccessPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RequestDatasourceAccessUserDatasourcesDatasourceIdRequestAccessPostError =
  RequestDatasourceAccessUserDatasourcesDatasourceIdRequestAccessPostErrors[keyof RequestDatasourceAccessUserDatasourcesDatasourceIdRequestAccessPostErrors];

export type RequestDatasourceAccessUserDatasourcesDatasourceIdRequestAccessPostResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetUserProfileUserProfileGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/user/profile';
};

export type GetUserProfileUserProfileGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type HealthCheckMetricsHealthGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/metrics/health';
};

export type HealthCheckMetricsHealthGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type RootGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/';
};

export type RootGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ClientOptions = {
  baseURL: `${string}://${string}` | (string & {});
};
