// This file is auto-generated by @hey-api/openapi-ts
import { z } from 'zod';

/**
 * Body_upload_file_kb_upload_post
 */
export const zBodyUploadFileKbUploadPost = z.object({
  file: z.string(),
});

/**
 * ChatRequest
 */
export const zChatRequest = z.object({
  message: z.string(),
});

/**
 * DataSourceInfo
 */
export const zDataSourceInfo = z.object({
  id: z.string(),
  name: z.string(),
  description: z.string(),
  tables: z.array(z.string()),
  access_level: z.string(),
  has_access: z.boolean(),
});

/**
 * FileInfo
 */
export const zFileInfo = z.object({
  id: z.string(),
  filename: z.string(),
  original_filename: z.string(),
  size: z.number().int(),
  upload_date: z.string(),
  file_type: z.string(),
  processing_status: z.string(),
  has_insight: z.boolean(),
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
  loc: z.array(z.union([z.string(), z.number().int()])),
  msg: z.string(),
  type: z.string(),
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
  detail: z.array(zValidationError).optional(),
});

/**
 * KnowledgeBaseInsightResponse
 */
export const zKnowledgeBaseInsightResponse = z.object({
  summary: z.string(),
  key_insights: z.array(z.string()),
  entities: z.array(z.string()),
  topics: z.array(z.string()),
  processing_time: z.union([z.number(), z.null()]).optional(),
});

/**
 * KnowledgeBaseResponse
 */
export const zKnowledgeBaseResponse = z.object({
  id: z.string(),
  filename: z.string(),
  original_filename: z.string(),
  file_type: z.string(),
  file_size: z.number().int(),
  upload_date: z.string(),
  processing_status: z.string(),
  download_url: z.string(),
  insight: z.union([zKnowledgeBaseInsightResponse, z.null()]).optional(),
});

/**
 * TextUploadRequest
 */
export const zTextUploadRequest = z.object({
  text: z.string(),
  title: z.string().optional().default('Text Input'),
});

/**
 * UserCreate
 */
export const zUserCreate = z.object({
  username: z.string(),
  password: z.string(),
  email: z.string().optional().default(''),
  full_name: z.string().optional().default(''),
});

/**
 * UserLogin
 */
export const zUserLogin = z.object({
  username: z.string(),
  password: z.string(),
});

/**
 * UserResponse
 */
export const zUserResponse = z.object({
  id: z.string(),
  username: z.string(),
  email: z.string(),
  full_name: z.string(),
  created_at: z.string().datetime(),
  role: z.string().optional().default('user'),
});

/**
 * UserSettingsResponse
 */
export const zUserSettingsResponse = z.object({
  vai_tro: z.string(),
  chi_nhanh: z.string(),
  pham_vi: z.string(),
  du_lieu: z.string(),
  datasource_permissions: z.array(z.string()),
});

/**
 * UserSettingsUpdate
 */
export const zUserSettingsUpdate = z.object({
  vai_tro: z.string(),
  chi_nhanh: z.string(),
  pham_vi: z.string(),
  du_lieu: z.string(),
  datasource_permissions: z.array(z.string()),
});

export const zRegisterAuthRegisterPostData = z.object({
  body: zUserCreate,
  path: z.never().optional(),
  query: z.never().optional(),
});

export const zConfirmSignupAuthConfirmSignupPostData = z.object({
  body: z.object({}),
  path: z.never().optional(),
  query: z.never().optional(),
});

export const zLoginAuthLoginPostData = z.object({
  body: zUserLogin,
  path: z.never().optional(),
  query: z.never().optional(),
});

export const zLogoutAuthLogoutPostData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

export const zRefreshTokenAuthRefreshPostData = z.object({
  body: z.object({}),
  path: z.never().optional(),
  query: z.never().optional(),
});

export const zForgotPasswordAuthForgotPasswordPostData = z.object({
  body: z.object({}),
  path: z.never().optional(),
  query: z.never().optional(),
});

export const zResetPasswordAuthResetPasswordPostData = z.object({
  body: z.object({}),
  path: z.never().optional(),
  query: z.never().optional(),
});

export const zGetCurrentUserInfoAuthMeGetData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * Successful Response
 */
export const zGetCurrentUserInfoAuthMeGetResponse = zUserResponse;

export const zNewChatChatNewPostData = z.object({
  body: zChatRequest,
  path: z.never().optional(),
  query: z.never().optional(),
});

export const zContinueChatChatContinueChatIdPostData = z.object({
  body: zChatRequest,
  path: z.object({
    chat_id: z.string(),
  }),
  query: z.never().optional(),
});

export const zGetChatHistoryChatHistoryGetData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

export const zDeleteChatByIdChatHistoryChatIdDeleteData = z.object({
  body: z.never().optional(),
  path: z.object({
    chat_id: z.string(),
  }),
  query: z.never().optional(),
});

export const zGetChatByIdChatHistoryChatIdGetData = z.object({
  body: z.never().optional(),
  path: z.object({
    chat_id: z.string(),
  }),
  query: z.never().optional(),
});

export const zGetMessageDataChatDataMessageIdGetData = z.object({
  body: z.never().optional(),
  path: z.object({
    message_id: z.string(),
  }),
  query: z.never().optional(),
});

export const zDownloadMessageDataChatDownloadMessageIdGetData = z.object({
  body: z.never().optional(),
  path: z.object({
    message_id: z.string(),
  }),
  query: z.object({
    format: z.enum(['json', 'csv', 'excel', 'pdf']),
  }),
});

export const zUploadFileKbUploadPostData = z.object({
  body: zBodyUploadFileKbUploadPost,
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * Successful Response
 */
export const zUploadFileKbUploadPostResponse = zKnowledgeBaseResponse;

export const zUploadTextKbKbUploadTextPostData = z.object({
  body: zTextUploadRequest,
  path: z.never().optional(),
  query: z.never().optional(),
});

export const zListKbKbListGetData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * Response List Kb Kb List Get
 * Successful Response
 */
export const zListKbKbListGetResponse = z.array(zFileInfo);

export const zGetKbInsightKbKbIdInsightGetData = z.object({
  body: z.never().optional(),
  path: z.object({
    kb_id: z.string(),
  }),
  query: z.never().optional(),
});

export const zDeleteKnowledgeBaseKbKbIdDeleteData = z.object({
  body: z.never().optional(),
  path: z.object({
    kb_id: z.string(),
  }),
  query: z.never().optional(),
});

export const zDownloadFileKbDownloadKbIdGetData = z.object({
  body: z.never().optional(),
  path: z.object({
    kb_id: z.string(),
  }),
  query: z.never().optional(),
});

export const zGetSettingsUserSettingsGetData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * Successful Response
 */
export const zGetSettingsUserSettingsGetResponse = zUserSettingsResponse;

export const zUpdateSettingsUserSettingsPostData = z.object({
  body: zUserSettingsUpdate,
  path: z.never().optional(),
  query: z.never().optional(),
});

export const zGetDatasourcesUserDatasourcesGetData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * Response Get Datasources User Datasources Get
 * Successful Response
 */
export const zGetDatasourcesUserDatasourcesGetResponse = z.array(zDataSourceInfo);

export const zGetAccessibleDatasourcesUserDatasourcesAccessibleGetData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * Response Get Accessible Datasources User Datasources Accessible Get
 * Successful Response
 */
export const zGetAccessibleDatasourcesUserDatasourcesAccessibleGetResponse =
  z.array(zDataSourceInfo);

export const zRequestDatasourceAccessUserDatasourcesDatasourceIdRequestAccessPostData = z.object({
  body: z.never().optional(),
  path: z.object({
    datasource_id: z.string(),
  }),
  query: z.never().optional(),
});

export const zGetUserProfileUserProfileGetData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

export const zGetUserIamRoleInfoUserIamRoleInfoGetData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

export const zHealthCheckMetricsHealthGetData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

export const zRootGetData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});
